name: Tag
on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    env:
      PACKAGE: hostname
      REPO: ghcr.io/octarect/hostname
    steps:
      - id: fetch
        name: Fetch a newest version tag
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          response="$(curl -sSfL \
            -H "Authorization: token $CR_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/users/$GITHUB_ACTOR/packages/container/$PACKAGE/versions)"
          latest_tag="$(echo "$response" | jq -r 'map(.metadata.container.tags) | flatten | .[]' | grep -E '^[0-9]' | sort -rV | head -n1)"
          echo "$latest_tag will be tagged as latest"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push latest tag
        env:
          TARGET_TAG: ${{ steps.fetch.outputs.latest_tag }}
        run: |
          docker image pull $REPO:$TARGET_TAG
          docker image tag  $REPO:$TARGET_TAG $REPO:latest
          docker image push $REPO:latest
